import 'package:flutter/material.dart';

abstract final class AppColors {
  static const primary = Color(0xFF2D5BFF);
  static const primaryButton = Color(0xFF2B5CE6);
  static const heading = Color(0xFF111827);
  static const headingAlt = Color(0xFF20212B);
  static const label = Color(0xFF191C1D);
  static const muted = Color(0xFF6B7280);
  static const placeholder = Color(0xFF70727D);
  static const helper = Color(0xFF8A8B96);
  static const terms = Color(0xFF464555);
  static const inputBorder = Color(0xFFC7C4D8);
  static const outline = Color(0xFFE7E8EB);
  static const pill = Color(0xFFF3F4F5);
  static const pillBorder = Color(0x4DC7C4D8);
  static const buttonGlow = Color(0x40635BFF);
  static const white = Color(0xFFFFFFFF);
  static const black = Color(0xFF000000);
  static const focusShadow = Color(0x402B5CE6);
  static const focusInset = Color(0x332B5CE6);

  // Onboarding
  static const slate = Color(0xFF0F172A);
  static const slateMuted = Color(0xFF64748B);
  static const slateSoft = Color(0xFF475569);
  static const slateBody = Color(0xFF334155);
  static const progressInactive = Color(0xFF9DB6FD);
  static const iconChip = Color(0xFFEEF2FF);
  static const iconChipSoft = Color(0xFFDFEDFF);
  static const cardBorder = Color(0xFFE2E8F0);
  static const radioBorder = Color(0xFFCBD5E1);
  static const continueGlow = Color(0xFFC7D2FE);
  static const gray50 = Color(0xFFF8FAFC);
  static const gray100 = Color(0xFFF1F5F9);
  static const gray200 = Color(0xFFE5E7EB);
  static const gray700 = Color(0xFF374151);
  static const gray800 = Color(0xFF1F2937);
  static const toggleOff = Color(0xFFCBD5E1);
  static const errorBg = Color(0xFFFEF2F2);
  static const errorBorder = Color(0xFFFEE2E2);
  static const errorText = Color(0xFFDC2626);
  static const warningBg = Color(0xCCFFFBEB);
  static const warningBorder = Color(0x99FDE68A);
  static const warningText = Color(0xFF78350F);
  static const overallBg = Color(0x80EEF2FF);
  static const overallBorder = Color(0x99E0E7FF);
  static const infoCardBg = Color(0x99EEF2FF);
  static const infoCardBorder = Color(0x99A1B7CE);
  static const targetBorder = Color(0xFFA1B7CE);
  static const dateHint = Color(0xFF94A3B8);
  static const dateSubtext = Color(0xFF8A8C8D);
  static const statsCard = Color(0xFFF7F8FF);
  static const listDivider = Color(0xFFCBD4DD);
  static const secondaryBtnBorder = Color(0xFFC7D2FE);

  // Diagnostic Test — Active (ONBD-006)
  static const diagPrimary = Color(0xFF2563EB);
  static const diagPrimaryShadow = Color(0x4D3B82F6);
  static const diagCardBorder = Color(0xFFE8EDF3);
  static const diagBannerBg = Color(0xFFF7F8FF);
  static const diagBannerBorder = Color(0xFFDBEAFE);
  static const diagTimerPillBg = Color(0xFFF1F5F9);
  static const diagTimerPillBorder = Color(0x99E2E8F0);
  static const diagTimerAlert = Color(0xFFE11D48);
  static const diagWaveformInactive = Color(0xFFB6BBC2);
  static const diagStatusBg = Color(0x80EFF6FF);
  static const diagStatusBorder = Color(0x99809CB3);
  static const diagStatusText = Color(0xFF1D4ED8);
  static const diagNoticeBg = Color(0xB3EFF6FF);
  static const diagNoticeBorder = Color(0xCCDBEAFE);
  static const diagOptionBorder = Color(0xFFE2E8F0);
  static const diagOptionSelectedBg = Color(0x4DEFF6FF);
  static const diagOptionText = Color(0xFF475569);
  static const diagCardBorderSoft = Color(0xCCE2E8F0);
  static const diagOptionSelectedBgSoft = Color(0x66EFF6FF);
  static const diagChipBg = Color(0xFFEFF6FF);
  static const diagContinueShadow = Color(0x402563EB);
  static const diagBodyText = Color(0xFF1E293B);

  // Dashboard / Home (DASH-001, DASH-002)
  static const dashBg = Color(0xFFF8FAFC);
  static const dashHeroGradientStart = Color(0xFF2563EB);
  static const dashHeroGradientEnd = Color(0xFF4F46E5);
  static const dashRingTrack = Color(0x33FFFFFF);
  static const dashRingProgress = Color(0xFFFFFFFF);
  static const dashCountdownBg = Color(0x26FFFFFF);
  static const dashBellDot = Color(0xFFEF4444);
  static const dashCardShadow = Color(0x0F0F172A);
  static const dashReadingIcon = Color(0xFF2563EB);
  static const dashReadingIconBg = Color(0xFFEFF6FF);
  static const dashWritingIcon = Color(0xFF7C3AED);
  static const dashWritingIconBg = Color(0xFFF5F3FF);
  static const dashListeningIcon = Color(0xFF059669);
  static const dashListeningIconBg = Color(0xFFECFDF5);
  static const dashPillBg = Color(0xFFF1F5F9);
  static const dashDoneBadgeBg = Color(0xFFDCFCE7);
  static const dashDoneBadgeText = Color(0xFF15803D);
  static const dashInsightBg = Color(0xFFFFFBEB);
  static const dashInsightBorder = Color(0xFFFDE68A);
  static const dashInsightIcon = Color(0xFFB45309);
  static const dashNavInactive = Color(0xFF94A3B8);

  // Daily Goal Complete overlay (DASH-002)
  static const goalOverlayScrim = Color(0xCC0F172A);
  static const goalCardShadow = Color(0x333B82F6);
  static const goalFlameBg = Color(0xFFFFF1E6);
  static const goalStreakCardBg = Color(0xFFFFF7ED);
  static const goalStreakCardBorder = Color(0xFFFED7AA);
  static const goalXpCardBg = Color(0xFFEFF6FF);
  static const goalXpCardBorder = Color(0xFFBFDBFE);
  static const goalMilestoneBg = Color(0xFFFFFBEB);
  static const goalMilestoneBorder = Color(0xFFFDE68A);
  static const goalMilestoneIconBg = Color(0xFFFDE68A);
  static const goalKeepGoingBg = Color(0xFFF8FAFC);
  static const goalKeepGoingBorder = Color(0xFFE2E8F0);
  static const goalKeepGoingIconBg = Color(0xFFEFF6FF);
  static const goalButtonShadow = Color(0x402563EB);
}
